### ISSUE TITLE
Wrong dependency for crm_claim_type

### ISSUE THREAD

**Issue by PieterPaulussen** [OCA/rma#108]
In the module crm_claim_rma_code there is a dependency to crm_claim_type. However, this module is not present in the repo.

**Comment by davinci41** [comment]
Uncaught Error: Nieznane pole claim_type w domenie ["|",["partner_id","=",false],["claim_type","in",["customer","other"]]]
odoo 8. please

**Comment by andhit-r** [comment]
Hi @PieterPaulussen crm_claim_type module avalaible on [OCA/crm repo](https://github.com/OCA/crm)

**Comment by davinci41** [comment]
Bug is in claim, can`t create new claim.
http://prnt.sc/edjv20

**Comment by andhit-r** [comment]
Hi @davinci41 , you should create new issue since your problem different from original question.

**Comment by PieterPaulussen** [comment]
@andhit-r Thanks, will check it out!
