### ISSUE TITLE
[RFC][9.0]RMA

### ISSUE THREAD

**Issue by AaronHForgeFlow** [OCA/rma#111]
# Introduction

The purpose of this RFC is to define the design for a RMA tool in Odoo. A beta version can be found in the PR https://github.com/OCA/rma/pull/110

## Why change the existing approach used in 7.0 and 8.0?
- Claims were designed for tracking customer claims and grievances not for a RMA process. Adding an RMA functionality to the claims makes it impossible to use claims for other processes. 
- Claims will be removed in 10.0
- We want to align more to the orthogonal design built by odoo in purchase and sales orders. Remove workflows.

Versions impacted: 9.0 and newer.
## Objectives
- Ease of use.
- Full traceability. The RMA is the central point of control of an often complex process. 
- Control of logistic and invoicing follow-up processes from the RMA.
- Flexibility. Acknowledging that such complex process will need to handle variations, the user must always be in control. Odoo must provide the relevant information at all times for a proper decision making, instead of restricting the actions of the user.

## Functional approach:
- We distinguish two basic types of RMA. Customer and Supplier.
- A Customer RMA can be created either from a sales order or a customer invoice.
- A Supplier RMA can be created either from a purchase order or a supplier invoice.
- Simple RMA approval workflow. Can be extended if needed by means of additional modules.
- Operations (replace, repair, refund) control the flow in each RMA line. They define how much is expected to be received, refunded and delivered. 
- The company can define default operations for each product category.
- The user can create the necessary pickings or refunds from the RMA lines.
- According to the operation requested (replace, repair or refund), the system will calculate key information for the user to make appropriate decisions: Qty to receive, Qty incoming, Qty to deliver, Qty to refund, Qty received, Qty outgoing, Qty delivered.
- There’s no constraint when creating moves or refunds. It’s possible to refund more quantity than the required or receive/send more quantity than the quantity required. The user will know the state of the RMA by looking at the quantities.
- When the user considers the process is finished he can set the RMA record to Done manually.
- From the RMA and RMA lines we have access to the sourced invoices and the sourced SO and PO if any, as well as to the generated refunds, receipts and deliveries.
- We can search by RMA number in the standard invoices, sale orders and purchase orders view. In the form view of them lines we will see the rma lines involved.

## Outstanding Issues
- Should it be possible to create RMA from Sale Order Lines or Purchase Order Lines that have not yet been invoiced?

**Comment by JordiBForgeFlow** [comment]
cc @nhomar You might be interested in this!

**Comment by rubencabrera** [comment]
This seems like a good approach. Given the state of development for 8.0 and its many issues, do you think this should be backported?

**Comment by JordiBForgeFlow** [comment]
@rubencabrera Not sure. That may need to be discussed. Our aim now is to work on 9.0 and 10.0

**Comment by rubencabrera** [comment]
@jbeficent Our team is working on some fixes for version 8.0, that's why we wonder if it's a good idea to backport your PR or better try to keep the crm_claim approach. I'll leave that open to suggestions while we keep on the current development.

**Comment by jgrandguillaume** [comment]
Hi there,

Just to mention that I'll support @aheficent proposition here. Very good move !

Regards,

Joël

P.S.  @jbaudoux I think we should move on this one as well for our common customer ;)
