### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by max3903** [OCA/rma#127]
* Support service products
* Integrate Vendor RMA
* Repair/Replace on site
* Carrier integration (label)
* Support different responsibilities distributions
* Instructions
* POS integration
* Refurbished product (replaced by another product)
* Flexible process/steps
* RMA Portal
* Script for CSR calls
* Quality integration / Problems
* Reporting

**Comment by pedrobaeza** [comment]
Very good roadmap. Do you have code already for this?

**Comment by max3903** [comment]
@pedrobaeza Nope. These are the ideas collected at the end of my Odoo Experience presentation.

**Comment by pedrobaeza** [comment]
OK, let's see if there are volunteers for implementing this roadmap.

**Comment by LoisRForgeFlow** [comment]
We have some implementation regarding some of these points:

* Problem tracking and QC integration: https://github.com/OCA/manufacture/pull/199
* Refurbishing: https://github.com/OCA/manufacture/pull/225

However we use a different base rma implamentation, you can have a look at: https://github.com/eficent/stock-rma I think we have addressed with it also the following points of your list:

* Integrate Vendor RMA
* Flexible process/steps

I just wanted to provide these implementations to try to reach some agreement and reduce the parallel works as much as possible.

**Comment by lukebranch** [comment]
I've had a request for a feature for an RMA flow where the customer may send back a single part/component of an assembled product (in this case a drone), where a single part may have a fault and require a replacement/repair/different product.

Before starting any work on it though, is this a feature that anyone else has already built (or has on a roadmap), or is interested in?
