### ISSUE TITLE
Master to replace by 8.0

### ISSUE THREAD

**Issue by yvaucher** [OCA/rma#14]

**Comment by yvaucher** [comment]
cc @jgrandguillaume @elicoidal @StefanRijnhart @max3903 @nhomar @sebastienbeau @gurneyalex

**Comment by StefanRijnhart** [comment]
Do you want me to rename master or push a fresh copy of the 7.0 branch to 8.0 with the new modules moved to **unported**?

**Comment by yvaucher** [comment]
The only 3 commits done in master are there to move modules to `__unported__` and master misses 37 commits from 7.0. I thinks it's a good idea to start a fresh one from 7.0

**Comment by StefanRijnhart** [comment]
Done!

close

**Comment by StefanRijnhart** [comment]
Anyone know how to close issues with a directive in an email reply, BTW?
