### ISSUE TITLE
wrong field name in `_refund_cleanup_lines` patch method

### ISSUE THREAD

**Issue by adamwojt** [OCA/rma#147]
There is mistake [here](https://github.com/OCA/rma/blob/f0656eb39c55081eff52ad502a0a1deb648b0822/crm_claim_rma/models/account_invoice.py#L42) that causes that `invoice_line_tax_ids` are not appended resulting in incorrect tax for refund invoice. 

`invoice_line_tax_id` should be `invoice_line_tax_ids`

[Odoo 10.0 account.invoice.line](https://github.com/odoo/odoo/blob/91807404e7d5c314ea30926b44bd16e878417ec1/addons/account/models/account_invoice.py#L1251)

**Comment by pedrobaeza** [comment]
Can you please do the PR? https://odoo-community.org/page/Contribute

**Comment by adamwojt** [comment]
Hey @pedrobaeza . Sure we will, we are reworking this method at the moment. 

We have better approach for patching this using index to update values from super and not copy/pasting original Odoo method as there are problems with current approach for example:

- `MAGIC_COLUMNS` are not excluded like in [original method](https://github.com/odoo/odoo/blob/91807404e7d5c314ea30926b44bd16e878417ec1/addons/account/models/account_invoice.py#L995).

We are also thinking that `tax_line_ids` should be dropped for refund invoice since we noticed problem when refund is made for less lines than original invoice - taxes are wrong (calculated for all lines of original invoice). All this can be easily achieved in this patch method.  

If dropped, new `tax_line_ids` will be recalculated anyway with [_onchange_invoice_line_ids](https://github.com/odoo/odoo/blob/91807404e7d5c314ea30926b44bd16e878417ec1/addons/account/models/account_invoice.py#L462)

**Comment by pedrobaeza** [comment]
OK, great. The code for this module can be very ugly, so any improvement is welcome. NOTE: I'm not a user of this module nor proper reviewer for it, but general community manager for this kind of kick-off.
