### ISSUE TITLE
[13.0] website_rma: Error on website contact form page.

### ISSUE THREAD

**Issue by Webimtech** [OCA/rma#196]
Hi,

I got a problem once I installed the module website_rma on the website contact form.
Odoo support specialist seems confirm that the module is interfering with the form. . By uninstalling it, the page "contact" works well!

![rma](https://user-images.githubusercontent.com/66035639/104705272-ff107680-5719-11eb-819b-b52bfd4f4c4d.png)

Thank you for checking this point.

Regards

**Comment by pedrobaeza** [comment]
Fixed already.
