### ISSUE TITLE
Multiple Products from Sale Order in Single RMA

### ISSUE THREAD

**Issue by mfaheemkhan6** [OCA/rma#204]
module: rma_sale
version: 13.0

**Steps to reproduce**
Open any sale order, create RMA for multiple products. It will create a separate RMA for each order line.
- ...

**Current behavior**
When we create RMA from the sale order, it is creating a separate RMA for each product in the sale order. 
**Expected behavior**
In a sale order, If one has 100 order lines, he has to handle 100 RMA and process 100 RMA to completely return the full order. It should depend on action, e.g. if we are going to refund all products then it should create a single RMA for all products. If we are going to refund some and replace or repair others, then we should create multiple RMA on our own.

**Comment by pedrobaeza** [comment]
This is not how it has been designed by several reasons. You can select all RMAs and select them to be refunded from the list view though.
