### ISSUE TITLE
[13] Community - Backorder issue with RMA module

### ISSUE THREAD

**Issue by sergioeix** [OCA/rma#224]
When rma is installed the backorder flow its not working as it should be, if you chose to not create backorder the backorder is still created.
Steps to reproduce on runbot:
1 create a sale order with 5 und of storable product
2 go to the delivery and set 2 und as done and validate
3 on the back order wizard chose no backorder
Result --> backorder is created
spected result --> no backorder should be created

Once rma module is unistalled backorder flow work as usual.

**Comment by sergioeix** [comment]
hi guys how its going on here? any new about this issue?? and #211
B/R

**Comment by victoralmau** [comment]
Hello, reviewing this use case, the current operation is correct, right?

![rma-13](https://user-images.githubusercontent.com/4117568/168551576-013496f7-e7e8-48e0-a92a-98cc341efedf.gif)

**Comment by sergioeix** [comment]
yes

**Comment by victoralmau** [comment]
Ok, we can close this issue.
