### ISSUE TITLE
[13.0] rma_sale translation

### ISSUE THREAD

**Issue by matteoopenf** [OCA/rma#242]
I'd like make a translation for italian language, but I can't create new translation
![image](https://user-images.githubusercontent.com/43987335/138494682-628f2fce-af70-409b-a448-43999c188a29.png)

Someone can help me to create the translation?

**Comment by matteoopenf** [comment]
@OCA/community-maintainers  can you help me please?
Thanks in advanced

**Comment by pedrobaeza** [comment]
https://odoo-community.org/page/translate

**Comment by matteoopenf** [comment]
> https://odoo-community.org/page/translate

Thanks
