### ISSUE TITLE
App RMA causes tests in sale_stock to fail during build

### ISSUE THREAD

**Issue by matthew798** [OCA/rma#245]
## Module
app RMA

## Describe the bug
After downloading V13 from [here](https://odoo-community.org/shop/product/app-rma-3326#attr=8968), the folder is placed in a DEV branch and pushed to an odoo sh instance. The build fails because a test in the sale_stock module fails.

## To Reproduce
**Affected versions**: V13

1. Create DEV branch with RMA app (v13) and upload
2. Allow odoo SH to build branch

**Expected behavior**
The module should not cause tests in other modules to fail

**Additional context**

11/10/2021 21:15:07 | ERROR | server | FAIL: TestSaleStock.test_03_sale_stock_delivery_partial Traceback (most recent call last):   File "/home/odoo/src/odoo/addons/sale_stock/tests/test_sale_stock.py", line 268, in test_03_sale_stock_delivery_partial     self.assertEqual(self.so.invoice_status, 'invoiced', 'Sale Stock: so invoice_status should be "invoiced" when set to done') AssertionError: 'no' != 'invoiced' - no + invoiced  : Sale Stock: so invoice_status should be "invoiced" when set to done
-- | -- | -- | --
11/10/2021 21:15:16 | ERROR | server | Module sale_stock: 1 failures, 0 errors

Other modules installed and working:
- mrp_production_request 13.0.1.0.1
- product_multi_category 13.0.1.0.0
- purchase_request 13.0.4.2.0
- sale_order_line_date 13.0.1.1.0
- stock_available_unreserved 13.0.1.0.1

**Comment by pedrobaeza** [comment]
This module is no way changing anything related to that, so the problem should be another. Closing as no valid issue.

**Comment by matthew798** [comment]
@pedrobaeza So i did some testing and removing sale_order_line_date fixes the problem. However, it is the _comibination_ of sale_order_line_date and rma that causes the issue, both work fine on their own...
