### ISSUE TITLE
[13.0] rma_sale: The license AGPL-3 conflicts with one of its dependencies.

### ISSUE THREAD

**Issue by dreispt** [OCA/rma#247]
Error on Odoo app store:

> rma_sale: The license AGPL-3 conflicts with one of its dependencies. Please make sure that you comply with the licenses compatibility. See our FAQ at https://apps.odoo.com/apps/faq#maintainer_faq_04 .

**Comment by pedrobaeza** [comment]
I think `rma` is registered by other repository, and thus the error, as OCA's `rma` is also AGPL-3.
