### ISSUE TITLE
Supplier RMA

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/rma#25]
Hello,

I am testing the RMA process. So far, it looks good to me for customer RMA. But what about the supplier-related RMA process? That is, from company to supplier. There's a claim type = Supplier that supposedly should be used for this sub-process. 

However I identified the following issues:
- When the claim is in status "In Progress": 
- When the user creates a new Delivery Order to send the product to the supplier the destination location is defaulted to 'Customer'. Should be 'Supplier' instead if the claim type is Supplier.
- When the user creates a new Products Return to receive the repaired/replaced product, the source location is defaulted to 'Customer'. Should be 'Supplier' instead if the claim type is Supplier.
- When the user creates a new Refund the selection list limits the Refund Journals to sales-related only. Should be a purchase-related refund journal if the claim type is Supplier.
- Also, it would be interesting to have an RMA label associated to the Stock Pickings.

See below a screenshot of the Supplier RMA process as I understand it:
![image](https://cloud.githubusercontent.com/assets/7683926/7728002/daac0018-ff0c-11e4-804c-86aa3caa35a6.png)

See also the Customer RMA process:
![image](https://cloud.githubusercontent.com/assets/7683926/7728174/d7b6d490-ff0d-11e4-8fd6-56cb66861b9f.png)

I will be working to improve the supplier RMA process. But will welcome the group's feedback!

Regards,
Jordi.

**Comment by nhomar** [comment]
Hello.

Can you take a look on this

https://github.com/OCA/rma/pull/26

We redesign several things in order to have both process, the one you mentioned is in our roadmap also.

Feedback is welcome.

REgards.

**Comment by JordiBForgeFlow** [comment]
Thanks @nhomar. I will review and provide feedback.
