### ISSUE TITLE
[RFC] 14.0 rma_sale: questions about quantities

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/rma#268]
Hi, I noticed two behaviors I'm unsure about:

1) RMA from SO for more products than those ordered

STEPS TO REPRODUCE
- create SO with deliverable products > confirm > validate picking
- back in SO: create RMA > input in popup a quantity higher than the one displayed >accept

CURRENT BEHAVIOR
RMA is created for qty inputted

REQUIRED BEHAVIOR
Is there a scenario where user would willfully create an RMA for more quantities than those ordered? Probably a warning of qty in RMA > qty ordered after clicking "accept" could be good to make sure

2) RMA from SO for more products than those delivered

STEPS TO REPRODUCE
- create SO with deliverable products > confirm > do NOT validate picking
- back in SO: create RMA > input in popup a quantity higher than the one displayed (0) >accept

CURRENT BEHAVIOR
RMA is created for qty inputted

REQUIRED BEHAVIOR
Again, I'm not sure what is the use case for creating RMAs for products that have not yet been delivered, but a warning could be useful in preventing errors. 

@ernestotejeda what is your opinion on this? Thanks!

**Comment by pedrobaeza** [comment]
Always indicate Odoo version, and both behavior were not allowed back in v12/v13 where we created it.

**Comment by francesco-ooops** [comment]
> Always indicate Odoo version, and both behavior were not allowed back in v12/v13 where we created it.

Thank you, you're right! @ernestotejeda do you think it's an intended change or something lost in migration? Shall we fix v.14?

**Comment by francesco-ooops** [comment]
> Always indicate Odoo version, and both behavior were not allowed back in v12/v13 where we created it.

Hmm, I see that behavior is currently the same in v.13 (user can create RMAs in SO for qty > ordered/delivered qty). I just think a warning can be a good compromise rather than blocking the action for user
