### ISSUE TITLE
[13.0] RMA refund amount error when the product price has a discount

### ISSUE THREAD

**Issue by FranciscoBigWings** [OCA/rma#289]
Error
When using the refund button from RMA which origin is a saleorder that includes a product with a discount, the originated rectified invoice uses the price_unit from sale.order.line and not the price_unit minus the discount

I have reproduced it in 13.0

1. Create a saleorder with  aproduct with a discount on the price and create an invoice
2. Create an RMA filling picking_id, move_id, product_id and procurement_group_id
3. Use action_refund from RMA
4. A rectified invoice is created with a higher amount than the sale invoice because it didnt take in account the discount

Secondly but I think it is known, rectified invoices originated from rma are not linked with the original invoice as they are while creating the recitified invoice directly from the original invoice while using account_invoice_refund_link

**Comment by victoralmau** [comment]
This works fine with `rma_sale`

![rma-13](https://user-images.githubusercontent.com/4117568/187887349-902ffff2-9cee-42d1-9de1-82f41fc60967.gif)

**Comment by FranciscoBigWings** [comment]
Indeed, it works well then, after testing with the module installed everything is correct.

rma_sale is needed for taking in account discounts while doing a refund through rma
