### ISSUE TITLE
[FEATURE] Create Returns via API (Magento)

### ISSUE THREAD

**Issue by aignermi** [OCA/rma#29]
Hi guys,

first of all can you give me a status of how far you are with the migration to v8?

Second is there an API to this module to create Returns from external systems? What I have in mind is to create a Return when I create a Credit Memo in Magento. The reason why I want that is first of all to have all returns in Odoo and second to make the corresponding stock booking and have the inventory in sync in Odoo - as we still have all our payment providers in Magento and use the Credit Memo feature there to automatically transfer the money to our customers.

Thanks,
Michael

**Comment by pedrobaeza** [comment]
I think this is unrelated to this repository (as it talks about Magento). I close.
