### ISSUE TITLE
While replacing a product on RMA order, will it generate a picking order?

### ISSUE THREAD

**Issue by suppliesterminal** [OCA/rma#347]
Here is the procedure:
1. click the button "replace"
<img width="764" alt="image" src="https://user-images.githubusercontent.com/76964092/230477948-c779ff6c-968f-493d-9f5a-68a124ef2e26.png">
2. fill the information on the popup window. Only warehouse here, not location
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/76964092/230478277-6e0def36-ce10-4591-ba3b-63f448e893e7.png">
3. only 1 working order is generated.
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/76964092/230477414-6d261a56-a4ab-42f6-97b1-2a1f643e315b.png">
4. it's from the location WH/OUTPUT
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/76964092/230477772-471a2e52-f2aa-4412-8b8e-86b548793374.png">

The question is: 
There is nothing in OUTPUT location. Should a picking order an a packing order be generated? 

(The warehouse's Outgoing Shipments is 3 steps). 

Is there anyone has any idea? Please give me a hand,  it will be appreciated.

**Comment by pedrobaeza** [comment]
For now, there's no support for several steps deliveries.

**Comment by suppliesterminal** [comment]
> For now, there's no support for several steps deliveries.

Hi Pedro, thank you for the feedback. 
I think it's not a big problem. I can run it with an internal transfer, from the STOCK to Output.
