### ISSUE TITLE
Validation error on install rma

### ISSUE THREAD

**Issue by aksanaetukfactory** [OCA/rma#359]
There is a validation error on install the rma module odoo 14 version

Validation Error
×
The operation cannot be completed: another model requires the record being deleted. If possible, archive it instead.

Model: Unknown (Unknown), Constraint: stock_move_move_rel_move_orig_id_fkey

**Comment by pedrobaeza** [comment]
It seems your DB is in an inconsistent state, but it's not related to the module itself. You should fix the corresponding DB constraints and relations. Closing as no issue with the module.
