### ISSUE TITLE
Add support for serial number

### ISSUE THREAD

**Issue by kubangab** [OCA/rma#381]
**Is your feature request related to a problem?**
When you select a product from the list there is no way to select what specific serial number the product has 

**Describe the solution you'd like**
After you selected the product and how many you should also be able to add the serial numbers that need to be send in for replacement, repair or refund..

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by pedrobaeza** [comment]
The serial number is put on the incoming picking, not on the RMA.

**Comment by kubangab** [comment]
I understand how it works now. But it would be good if you can enter it already when creating the RMA so that the products that are returned are matched toward the products that is registered before. Also when the mail for return is send to the customer it would be good to include the serial numbers on the return form.

**Comment by pedrobaeza** [comment]
Yeah, it can be a nice to have, but you have to take into account that the number can be more than 1. Feel free to propose a pull request adding such features.
