### ISSUE TITLE
RMA - require operation

### ISSUE THREAD

**Issue by jbaudoux** [OCA/rma#404]
### Make the rma operation required

As multiple rma operations (return, refund, replace...) are available, I find it important that the user explicitly choose the operation for each product

In rma:
- [ ] Keep the field optional on the rma but require a value when confirming the rma (by adding to _ensure_required_fields) as this dictates what to do on confirmation

In rma_sale:
- [ ] In the SO create rma wizard, add before the list of products an optional field to set the default operation for all the lines. Make on all product lines the operation computed stored based on that default operation
- [ ] In the SO create rma wizard, on each product line, make the field required if qty > 0 as this wizard confirms the rma which require an operation to be set

**Comment by chienandalu** [comment]
They are mandatory at the portal. In the backend, it could be that a powerless user could not fit an RMA into the existing operation options... but I don't have a strong opinion about it :)

**Comment by pedrobaeza** [comment]
It isn't mandatory because certain flows create the RMAs without that operation defined (and the state in draft), and it should be filled later. If I don't remember bad:

- RMA creation through alias.
- RMAs from sales orders.

To make it required, these flows should be fixed somehow.

**Comment by sbejaoui** [comment]
IMO, it would be better to make this configurable in the rma_sale module as a company policy: RMA: Operation required. 
If it is activated, the field becomes required in the wizard and the RMA form view, so a salesperson cannot create the RMA order without setting the reason.
However, for other automatic flows, the creation continues, and the RMA team will fill in the operation later, but cannot process it before doing so.

**Comment by jbaudoux** [comment]
Thanks for your feedback. I updated the description with this proposal:
In rma:
- Keep the field optional on the rma but require a value when confirming the rma (by adding to _ensure_required_fields) as this dictates what to do on confirmation

In rma_sale:
- In the SO create rma wizard, add before the list of products an optional field to set the default operation for all the lines. Make on all product lines the operation computed stored based on that default operation
- In the SO create rma wizard, on each product line, make the field required if qty > 0 as this wizard confirms the rma which require an operation to be set
