### ISSUE TITLE
RMA Configure operation for when to generate stock transfer and how to manage invoicing

### ISSUE THREAD

**Issue by jbaudoux** [OCA/rma#408]
1. When you create an RMA for product replacement, currently the delivery is created only once the product is received. When you manage the transport, you prefer to make the exchange at the customer. For this, you need to generate the delivery when the rma is confirmed so that you can pick the product, bring it to the customer and take back the faulty returned product.
2. When you manage your invoicing from a sales order, you prefer to update the quantity delivered on the SO line instead of creating a credit note out of the rma. This allows to respect invoicing policy such as at the end of the month and group all deliveries and returns.
3. Allow to configure that you don't want to generate a refund, for example in the case of repair where the product still belongs to the customer.

This is somehow implemented in the PR https://github.com/OCA/rma/pull/334 from @mt-software-de
I propose to extract from there the mentioned features and port to v16

**Comment by pedrobaeza** [comment]
For point 2, we can have a button for just calling this method:

https://github.com/OCA/rma/blob/3436ec67afb63e438252a043e35a51173548bf0b/rma_sale/models/rma.py#L96

And an extra RMA state for considering it finished that way.

Nothing more is needed.

**Comment by jbaudoux** [comment]
Thanks for the feedback. `_link_refund_with_reception_move` could be used for having the right settings on the reception move after its creation.
But I would like to configure this on the operation as once the RMA is created, the chosen operation will dictate the process and nobody will look at the rma anymore (or click a button) unless the customer comes back to the after-sales service.

**Comment by sbejaoui** [comment]
covered by #413

**Comment by jbaudoux** [comment]
Replaced by https://github.com/OCA/rma/issues/413
