### ISSUE TITLE
Can't Install 8.0 branch on Odoo 8.0 - requires  'crm_claim_type' but it's not available?

### ISSUE THREAD

**Issue by MDBenson** [OCA/rma#64]
I am trying to install 8.0 on my Odoo 8.0 test instance (clean, new database) and it seems to have an unresolved module dependency.

Procedure:
- Cloned fresh Odoo 8.0 into /opt/odoo
- Cloned fresh RMA 8.0 then copied:
  - crm_claim_categ_as_name
  - crm_rma_by_shop
  - crm_rma_stock_location
  - crm_claim_ext
  - crm_rma_location
  - crm_claim_rma
  - crm_rma_lot_mass_return
  - crm_claim_rma_code
  - crm_rma_prodlot_invoice
  - product_warranty
  - crm_rma_advance_location
  - crm_rma_prodlot_supplier
    to /opt/odoo/addons
- Ran 'Update Modules List' in Odoo 8.0
- Attempted to install 'crm_claim_rma'
- Error shown (see pic attached)

![rma-broken](https://cloud.githubusercontent.com/assets/4146140/11271405/7f2c0bac-8ebd-11e5-8977-081e89719aa2.png)

**Comment by osvalr** [comment]
@MDBenson `crm_claim_type` module can be found here [OCA/crm](https://github.com/OCA/crm/tree/8.0)

**Comment by MDBenson** [comment]
Thanks for the update. Is there some structure for adding all OCA modules en-mass or do we just have to play dependency roulette? Might be worth mentioning dependencies in the README?

**Comment by pedrobaeza** [comment]
They are usually mentioned in Installation section if they are not from the same repository, but there's no automatic script for resolving then. We are working in pip deployment with auto-dependency now, but there are some challenges to solve. You can look here for more info: https://github.com/OCA/maintainer-tools/pull/156.

For downloading all OCA branches (but there's a lot), you can use: https://github.com/OCA/maintainer-tools/blob/master/tools/clone_everything.py

**Comment by MDBenson** [comment]
Okay, thanks. As the README for this repo (rma) is very minimal for the 8.0 branch, it was not stated as there is no Installation section in the README.

**Comment by pedrobaeza** [comment]
I mean the README.rst of each module, not the repo one. Each module can be installed separately, so there's no sense to make a global dependency map by repo.
