### ISSUE TITLE
[8.0] crm_rma_lot_mass_return gives javascript error on playAlert

### ISSUE THREAD

**Issue by RoelAdriaans** [OCA/rma#69]
With crm_rma_lot_mass_return installed, adding products we get an error:

`ReferenceError: playAlert is not defined`

Linked to https://github.com/OCA/rma/blob/8.0/crm_rma_lot_mass_return/static/src/js/barcode_text.js#L67 and https://github.com/OCA/rma/blob/8.0/crm_rma_lot_mass_return/static/src/js/barcode_text.js#L84 .. 

Tested with Firefox 43 on Linux, Chrome on Windows

**Comment by RoelAdriaans** [comment]
Linked to https://github.com/OCA/rma/blob/8.0/crm_rma_lot_mass_return/templates/search_view.xml#L6

The file /crm_rma_lot_mass_return/static/lib/alert.js does not exist.

ping @osvalr , because you've committed this code, maybe left behind in a .gitignore?

**Comment by osvalr** [comment]
@RoelAdriaans-B-informed I'm checking this out

**Comment by osvalr** [comment]
@RoelAdriaans-B-informed as you pointed out `alert.js` was ignored by the `.gitignore` and it's necessary to allow this file allow `../static/lib` but maintain the rule for generic `/lib` as it's currently listed

**Comment by RoelAdriaans** [comment]
@osvalr True, but you can to an git add -f <filename> to add the file, ignoring the gitignore file

**Comment by osvalr** [comment]
@RoelAdriaans-B-informed but valid directories as `static/lib/` need be added without any forcing IMHO, please see OCA/maintainer-tools#173 and let me know your comments

**Comment by gurneyalex** [comment]
https://github.com/OCA/maintainer-tools/pull/173 is now merged

**Comment by gurneyalex** [comment]
The correct template gitignore file is https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.gitignore though

**Comment by RoelAdriaans** [comment]
Thanks for the merge @gurneyalex 
.gitignore is now updated, and file can be added cleanly.

**Comment by RoelAdriaans** [comment]
Fixed with the merging of #75
