### ISSUE TITLE
Work flow

### ISSUE THREAD

**Issue by krijn1981** [OCA/rma#79]
Hey guys,

Is there a roadmap for this collection of RMA modules.
We just installed it and trying to follow of it.
But we are stuck on the state change of the claim lines.

Perhaps we are making a proces flow error...
I already saw the short flow description in readme file, but that is to short for a complete following of the process.

Thanks in advance..

**Comment by marcverspeek** [comment]
Any progress Krijn? We have the same question. We do not succeed to change the status of a claim line.

**Comment by willdz** [comment]
Any luck with this? I am in the same situation.

**Comment by rubencabrera** [comment]
I am interested in this too, it seems like things are **almost** there but lacking some minor changes. I'm working on it, so if you find anything for the basic workflow, mention me and I'll try.

**Comment by aitorbouzas** [comment]
Is there anyone using succesfully the RMA modules? I'm also stuck on the change of state in the claim lines...

**Comment by aitorbouzas** [comment]
Maybe I can contribute in something.

I saw that the product_returned_quantity in the claim line is always 0.0... As I see into my crm_claim_rma/crm_claim.py file at line 135:

`'product_returned_quantity': invoice_line.quantity,`

It should have the same value as in the invoice line, but it's not!

**Comment by rubencabrera** [comment]
Hi, @Softdil , please check the PR #103 , it works for me on the issue you are mentioning.
